# Generated by Django 4.0.2 on 2022-10-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default=None, upload_to='gallery'),
        ),
    ]
